### ISSUE TITLE
un import fait planté le build webpack d'electron.

### ISSUE THREAD

**Issue by crakjie** [crakjie/electron-react-boilerplate#1]
[import ffbinaries from 'ffbinaries';](https://github.com/crakjie/Convex/blob/master/app/index.js#L4) fait plenté le build généré par `npm run package-win` avec le message d'erreur bien explicite suivant : `ERROR in unknown: Invalid number (30958:15)`

ffbinairies est une lib qui sert a télécharger la dèrniere version d'ffmpeg. 

Je vais aller voir si le problème est connus de la lib. 
Mais peut etre que le code n'est pas du tout la ou il le faut. (apres tout j'y connais rien, ceci dit ca fessais le taf en dev )
Sinon il me semble qu'il y a une version d'electron qui contiens deja ffmpeg.

@Florian-R

**Comment by crakjie** [comment]
Apres discution avec Vox le mec qui a fait ffbinarie il m'a dit qu'une des solution pour avoir ffmpeg et la suivante :
```
"scripts": { "postinstall": "ffbinaries ffmpeg --output=ffmpeg-target" }
```

evidament ca ne fonctionne pas au premier coup

**Comment by Florian-R** [comment]
J'ai pas eu le temps de creuser pour l'instant, mais a vue de nez, est ce que tu as refait un ``npm install` pour rerun le script de postinstall?

**Comment by crakjie** [comment]
Enfait si je met ffbinaries dans le postinstall du package.json qui est dans `app`, le dossier `ffmpeg-target` aparais dans `app` mais il n'est pas dans le build. L'idéal ce serais que ce soit run juste avant l'exécution comme sa, ffbinaries va chercher le binaire qui correspond a la platforme de l'utilisateur.

**Comment by crakjie** [comment]
Il m'a fallus du temps mais j'ai fini par entre apercevoir une des solution possible. 
C'est encore branlant mais avec un peut plus de comprehension de [electron-builder](https://github.com/electron-userland/electron-builder) sa iras mieu
